/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UcCompChild {
    }
    interface UcCompGrandparent {
        "name": string;
    }
    interface UcCompParent {
        "name": string;
    }
    interface UcSpinner {
    }
    interface UcStockFinder {
    }
    interface UcStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLUcCompChildElement extends Components.UcCompChild, HTMLStencilElement {
    }
    var HTMLUcCompChildElement: {
        prototype: HTMLUcCompChildElement;
        new (): HTMLUcCompChildElement;
    };
    interface HTMLUcCompGrandparentElement extends Components.UcCompGrandparent, HTMLStencilElement {
    }
    var HTMLUcCompGrandparentElement: {
        prototype: HTMLUcCompGrandparentElement;
        new (): HTMLUcCompGrandparentElement;
    };
    interface HTMLUcCompParentElement extends Components.UcCompParent, HTMLStencilElement {
    }
    var HTMLUcCompParentElement: {
        prototype: HTMLUcCompParentElement;
        new (): HTMLUcCompParentElement;
    };
    interface HTMLUcSpinnerElement extends Components.UcSpinner, HTMLStencilElement {
    }
    var HTMLUcSpinnerElement: {
        prototype: HTMLUcSpinnerElement;
        new (): HTMLUcSpinnerElement;
    };
    interface HTMLUcStockFinderElement extends Components.UcStockFinder, HTMLStencilElement {
    }
    var HTMLUcStockFinderElement: {
        prototype: HTMLUcStockFinderElement;
        new (): HTMLUcStockFinderElement;
    };
    interface HTMLUcStockPriceElement extends Components.UcStockPrice, HTMLStencilElement {
    }
    var HTMLUcStockPriceElement: {
        prototype: HTMLUcStockPriceElement;
        new (): HTMLUcStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "uc-comp-child": HTMLUcCompChildElement;
        "uc-comp-grandparent": HTMLUcCompGrandparentElement;
        "uc-comp-parent": HTMLUcCompParentElement;
        "uc-spinner": HTMLUcSpinnerElement;
        "uc-stock-finder": HTMLUcStockFinderElement;
        "uc-stock-price": HTMLUcStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface UcCompChild {
    }
    interface UcCompGrandparent {
        "name"?: string;
    }
    interface UcCompParent {
        "name"?: string;
    }
    interface UcSpinner {
    }
    interface UcStockFinder {
        "onUcSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface UcStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "uc-comp-child": UcCompChild;
        "uc-comp-grandparent": UcCompGrandparent;
        "uc-comp-parent": UcCompParent;
        "uc-spinner": UcSpinner;
        "uc-stock-finder": UcStockFinder;
        "uc-stock-price": UcStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uc-comp-child": LocalJSX.UcCompChild & JSXBase.HTMLAttributes<HTMLUcCompChildElement>;
            "uc-comp-grandparent": LocalJSX.UcCompGrandparent & JSXBase.HTMLAttributes<HTMLUcCompGrandparentElement>;
            "uc-comp-parent": LocalJSX.UcCompParent & JSXBase.HTMLAttributes<HTMLUcCompParentElement>;
            "uc-spinner": LocalJSX.UcSpinner & JSXBase.HTMLAttributes<HTMLUcSpinnerElement>;
            "uc-stock-finder": LocalJSX.UcStockFinder & JSXBase.HTMLAttributes<HTMLUcStockFinderElement>;
            "uc-stock-price": LocalJSX.UcStockPrice & JSXBase.HTMLAttributes<HTMLUcStockPriceElement>;
        }
    }
}
